# just a copy of the main docker-compose
version: '3.8'
services:
  # Docker connection string: postgres://postgres:postgres@localhost:5432/
  bsc-project-database:
    image: "postgres"
    container_name: "bsc-project-database"
    hostname: "bsc-project-database"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456ABCabc"
      POSTGRES_DB: "bsc-project-database"
    volumes:
      - bsc-project-volume:/var/lib/postgresql/data
    ports:
      # systemPort:containerPort
      - "5432:5432"

  bsc-project-backend:
    container_name: "bsc-project-backend"
    image: "bsc-project-backend"
    hostname: "bsc-project-backend"
    restart: always
    build:
      context: ./bsc-project-backend
    environment:
      DATABASE_URL: "postgresql://postgres:123456ABCabc@bsc-project-database:5432/bsc-project-database?schema=public"
      JWT_SECRET: "I'm a super secret!"
      JWT_EXPIRATION: "5d"
      APP_DOMAIN: "http://localhost:3000"
      API_DOMAIN: "http://localhost:5000"
      PORT: "5000"
    depends_on:
      - bsc-project-database
    command: ./docker-entrypoint.sh
    ports:
      - "5000:5000"


  bsc-project-frontend:
    container_name: "bsc-project-frontend"
    image: "bsc-project-frontend"
    restart: always
    build:
      context: ./bsc-project-frontend
    depends_on:
      - bsc-project-backend
    command: ./docker-entrypoint.sh
    ports:
      - "3000:3000"


volumes:
  bsc-project-volume: