# this docker-compose file generates a mock database for the development in local - not needed on server - production
version: '3.8'
services:
  # Docker connection string: postgres://postgres:postgres@localhost:5432/
  bsc-project-database:
    image: postgres
    container_name: bsc-project-database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456ABCabc
      POSTGRES_DB: bsc-project-database
    volumes:
      - bsc-project-volume:/var/lib/postgresql/data
    ports:
      # systemPort:containerPort
      - "5436:5432"
    networks:
      - bsc-project-network

networks:
  bsc-project-network:

volumes:
  bsc-project-volume: