# this docker-compose file generates a mock database for the development in local - not needed on server - production
version: '3.8'
services:
  # Docker connection string: postgres://postgres:postgres@localhost:5432/
  nest-framework-database:
    image: postgres
    container_name: nest-framework-database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456ABCabc
      POSTGRES_DB: nest-framework
    volumes:
      - nest-framework:/var/lib/postgresql/data
    ports:
      # systemPort:containerPort
      - "5434:5432"
    networks:
      - nest-framework

  test-nest-framework-database:
    image: postgres
    container_name: test-nest-framework-database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456ABCabc
      POSTGRES_DB: nest-framework
    volumes:
      - nest-framework:/var/lib/postgresql/data
    ports:
      # systemPort:containerPort
      - "5435:5432"
    networks:
      - nest-framework

networks:
  nest-framework:

volumes:
  nest-framework: